# Change these first
owner: Reathe # Your GitHub organization or username, where this repository lives
repo: ratflix-uptime # The name of this repository

sites:
  - name: Overseerr
    url: https://overseer.rafserver.com
  - name: Plex
    url: https://plex.rafserver.com/web/index.html#!

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rafserver.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Ratflix** status page."
  introMessage: "This page is used to monitor the status of our services."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  footer: Ratflix

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
